# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6aaaa35dbf8d38493167331b1fc59e3c"
name = "Just in Time Inventory"
handle = "just-in-time-inventory"
application_url = "https://conditional-hamburg-dress-kodak.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,read_locations"

[auth]
redirect_urls = ["https://conditional-hamburg-dress-kodak.trycloudflare.com/auth/callback", "https://conditional-hamburg-dress-kodak.trycloudflare.com/auth/shopify/callback", "https://conditional-hamburg-dress-kodak.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
